### ISSUE TITLE
[BUG] Cannot change Auto-Backup Folder when already enabled

### ISSUE THREAD

**Issue by theAkito** [keshav-space/safenotes#58]
**Describe the bug**
Changing the auto-backup destination folder is not possible, if the feature was already enabled.

**To Reproduce**
1. Enable Auto-Backup.
2. Go out of the Auto-Backup settings.
3. Enter Auto-Backup Settings.
4. You cannot change the destination folder.
5. You must disable and enable Auto-Backup to be able to change the destination folder.

**Expected behavior**
The folder should be changeable after the feature has been enabled.

**Comment by keshav-space** [comment]
Once you choose a backup destination for the first time immediately a backup is scheduled and gets triggered around ~10-15 sec during that time you can not change the folder. Once the first backup is done you can always change the folder without any problem.

See the below video from Pixel 4 running android@11

https://user-images.githubusercontent.com/44315208/198842659-a1455926-1cbe-475c-b166-eebf43cbeac4.mp4

**Comment by theAkito** [comment]
>Pixel 4 running android@11

Via an emulator?

I tested your claim and it isn't the case on my phone.

Your video also does not represent what is happening on my phone. In your video, the buttons are never greyed out. On my phone, they are always greyed out, once the backup is enabled. No matter how long I wait or if I quit the app, etc. It always stays greyed out.

Running this on Android 11 based custom ROM.

**Comment by keshav-space** [comment]
> Via an emulator?

Yeah, it's an emulator.

Seems like I was able to reproduce your problem this time.
Can you confirm this is what you were facing?

https://user-images.githubusercontent.com/44315208/198877855-7811842f-b1af-4bd5-a102-35945fd621fc.mp4

**Comment by theAkito** [comment]
> @theAkito can you confirm this is what you were facing?

No. The video shows the behaviour as you described earlier. Wati for the background job to complete, etc. Then it will work, etc.

In my case:

1. It does not matter how long you wait.
2. Both buttons are greyed out. In none of your videos are both greyed out permanently.
3. It does not change anything, if you go out and go into the Auto Backup screen, again. It remains greyed out. You may re-enter the app and both buttons remain greyed out permanently.

**Comment by keshav-space** [comment]
> No. The video shows the behaviour as you described earlier. Wait for the background job to complete, etc. Then it will work, etc.

but if you see from 0:58-1:02 it's grayed out just like you pointed out.

**Comment by theAkito** [comment]
> but if you see from 0:58-1:02 it's grayed out just like you pointed out.

Okay, but it happens for you only later. For me, it happens instantly, permanently. It is never not greyed out. It's always instantly greyed out for me, forever, after enabling Auto Backup.

**Comment by keshav-space** [comment]
Thanks, @theAkito  for reporting this 🙇 

I think I figured out what's causing this problem fix is on the way.

**Comment by keshav-space** [comment]
@theAkito If you want you can test out the fixed version from the pull request. Don't forget to export your data using `Manual Export` before removing the existing app.

**Comment by landry314** [comment]
I have the same issue; it is always grey once turned on no matter what.

From reading above it seems like this is because the backup just isn't working. You are saying above it should be changeable after 15 seconds after the first backup is complete. I never have a backup work. I have tried manual and automatic and it will not make a file.

The permissions are to allow access "to media only". I don't know why this is how the permission is written but maybe this is why. I am choosing /sdcard/Backup/ as my folder. Nothing.

I have a Pixel 5 running LineageOS 19.1

**Comment by keshav-space** [comment]
@landry314 issue is fixed in #59 
If you want you can test it out with this apk [signed-safenotes-all.apk.zip](https://github.com/keshav-space/safenotes/files/9896757/signed-safenotes-all.apk.zip) don't forget to keep a copy of your data by using `Manual Export` from settings.

**Comment by landry314** [comment]
I cant test the apk above because it has a different signature from my fdroid version and I can't make a backup first... so I have to wait for the next fdroid version.

**Comment by keshav-space** [comment]
> I cant test the apk above because it has a different signature from my fdroid version and I can't make a backup first... so I have to wait for the next fdroid version.

No problem, I have just issued the new release and should be available on fdroid by the end of next f-droid build cycle.

**Comment by landry314** [comment]
i got the new release and the backup is still not working. same as before. both in manual export and in auto backup you are asked to choose a folder and when i chose /sdcard/Backup it just moves on without creating a backup file.

**Comment by keshav-space** [comment]
1. Can you see the green lock here?

![Simulator Screen Shot - iPhone 11 - 2022-10-21 at 03 04 03](https://user-images.githubusercontent.com/44315208/200291080-83e6cbfc-e594-4267-9b15-3759e08e1ee4.png)
2. It's not working on internal storage too?
3. In that case I would need to reproduce this problem locally. Maybe lineageos is handling permissions differently. Do let me know if you know of any emulators for lineageos.

**Comment by landry314** [comment]
i see the green lock. internal storage? my path is /sdcard/Backup/ . i can not access the /Android/data/ folder where your internal app has external access. i am on a rooted device and i looked where i could.

**Comment by keshav-space** [comment]
> i see the green lock.

That's strange, the green lock is shown if and only if the backup file exists.
Have you used a different file explorer to confirm if the file exists?

The only way forward in my opinion is to somehow reproduce this problem on lineageos, let's see what I can do.

**Comment by theAkito** [comment]
Wanted to test this one again.

Now, it can only be enabled & disabled. No custom folder may be chosen.

Is this intended?

**Comment by landry314** [comment]
yes it is. android is moving towards not allowing apps to choose folders to save to. downloads is open and the Android/data folder which confuses people. this is the best solution. stick it in downloads.
